name: Bug report
description: "Something isn't working, or doesn't work as expected"
title: "bug: "
labels: ["bug", "pending-verification"]
body:
  - type: markdown
    attributes:
      value: |
        **For non-English users**
        
        It's okay to post in your language, but remember to use English for the body (you can paste the result of Google Translate or LLM), and put everything else as attachments.
        Issues with a non-English body will be DIRECTLY CLOSED until it's updated.
  
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected behavior"
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "How to reproduce?"
      description: A step-by-step reproduce process. A minimum repro repo is welcome.
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: "Environment"
      description: Check the Logto environment you are using.
      options:
        - Logto Cloud
        - Self-hosted (Docker image)
        - Self-hosted (Node.js)
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
