name: Feature request
about: Suggest an idea for this project
title: "feature request: "
labels: ["feature-request"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        For non-English users:
        
        It's okay to post in your language, but remember to use English for the body (you can paste the result of Google Translate), and put everything else as attachments.
        Issues with a non-English body will be DIRECTLY CLOSED until it's updated.

  - type: textarea
    id: problem
    label: What problem did you meet?
    description: A clear and concise description of what the problem is.

  - type: textarea
    id: need
    label: "Describe what you'd like Logto to have"
    description: A clear and concise description of what you want to happen.
